version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb-go-user-grpc
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
